[package]
name = "lspire"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"
bevy_rapier3d = "0.29"
noise = "0.9"
rodio = "0.19"
rand = "0.8"
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
local-ip-address = "0.6"
